name: Build Windows CLI

on:
  push:
    tags: ['v*']      # build when you push a tag like v0.1.2
  workflow_dispatch:   # or build manually from the Actions tab

jobs:
  build-win:
    runs-on: windows-latest
    permissions:
      contents: write   # needed to upload to the release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        shell: pwsh
        run: |
          # Add --collect-binaries soundfile if you use soundfile (pulls libsndfile).
          pyinstaller --onefile --name alak --collect-binaries soundfile cli/main.py

      - name: Prepare package
        shell: pwsh
        run: |
          $ver = "${{ github.ref_name }}"
          New-Item -ItemType Directory -Force -Path pkg | Out-Null
          @'
ALAK Windows CLI

Usage:
  alak.exe --help

SmartScreen:
  If you see a warning, click "More info" -> "Run anyway" (until we code-sign).
'@ | Set-Content -Path pkg/README_windows.txt -Encoding UTF8
          Copy-Item -Path dist/alak.exe -Destination pkg/
          Compress-Archive -Path pkg/* -DestinationPath "alak-win64-$ver.zip"

      - name: SHA256 checksum
        shell: pwsh
        run: |
          $zip = "alak-win64-${{ github.ref_name }}.zip"
          (Get-FileHash $zip -Algorithm SHA256).Hash.ToLower() | Out-File -Encoding ascii -NoNewline "SHA256SUMS.txt"

      - name: Upload to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            alak-win64-${{ github.ref_name }}.zip
            SHA256SUMS.txt
