name: Build Windows CLI

on:
  push:
    tags:
      - 'v*'            # build on tags like v0.1.3
  workflow_dispatch:     # allow manual run

permissions:
  contents: write        # allow release uploads

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --name alak cli/main.py

      - name: Package ZIP (with README)
        shell: pwsh
        run: |
          $ver = "${{ github.ref_name }}"
          New-Item -ItemType Directory -Force -Path pkg | Out-Null
          @"
ALAK Windows CLI

Usage:
  alak.exe --help

SmartScreen:
  If you see a warning, click 'More info' -> 'Run anyway' (until we code-sign).
"@ | Set-Content -Path pkg/README_windows.txt -Encoding UTF8
          Compress-Archive -Path dist/alak.exe, pkg/README_windows.txt -DestinationPath "pkg/alak-win64-$ver.zip"

      - name: Upload artifact (for CI)
        uses: actions/upload-artifact@v4
        with:
          name: alak-win64-${{ github.ref_name }}
          path: pkg/alak-win64-${{ github.ref_name }}.zip

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: pkg/alak-win64-${{ github.ref_name }}.zip
          fail_on_unmatched_files: true
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
