name: build-windows-alak
on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          pip install pyinstaller

      - name: Build EXE
        shell: pwsh
        run: |
          pyinstaller --onefile --name alak cli/main.py
          Get-ChildItem dist

      - name: Prepare artifacts
        shell: pwsh
        run: |
          $ver = "${{ github.ref_name }}"
          New-Item -ItemType Directory -Force -Path pkg | Out-Null
          $readme = @"
          ALAK Windows CLI

          Usage:
            alak.exe --help

          SmartScreen:
            If you see a warning, click "More info" -> "Run anyway" (until we code-sign).
          "@
          Set-Content -Path pkg/README_windows.txt -Value $readme -Encoding UTF8
          $zip = "pkg/alak-win64-$ver.zip"
          Compress-Archive -Path dist/alak.exe, pkg/README_windows.txt -DestinationPath $zip -Force

      - name: SHA256 checksum
        shell: pwsh
        run: |
          $zip = Get-ChildItem pkg\*.zip | Select-Object -First 1
          $hash = (Get-FileHash $zip.FullName -Algorithm SHA256).Hash.ToLower()
          "$hash  $($zip.Name)" | Out-File pkg\SHA256SUMS.txt -Encoding ascii
          Get-Content pkg\SHA256SUMS.txt

      - name: Upload release assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pkg/*.zip
            pkg/SHA256SUMS.txt
