name: Build Windows CLI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install -U pip wheel
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          pip install pyinstaller sounddevice soundfile msgpack numpy

      - name: Build EXE with PyInstaller
        shell: pwsh
        run: |
          pyinstaller --onefile --name alak `
            --hidden-import sounddevice `
            --hidden-import soundfile `
            cli/main.py

      - name: Prepare artifacts
        shell: pwsh
        run: |
          $ver = "${{ github.ref_name }}"
          New-Item -ItemType Directory -Force -Path pkg | Out-Null

          # README without here-strings (YAML-safe)
          $readmeLines = @(
            'ALAK Windows CLI',
            '',
            'Usage:',
            '  alak.exe --help',
            '',
            'SmartScreen:',
            '  If you see a warning, click "More info" -> "Run anyway" (until code-signed).'
          )
          $readme = $readmeLines -join "`n"
          Set-Content -Path pkg/README_windows.txt -Value $readme -Encoding UTF8

          # Zip + checksum
          $zip = "pkg/alak-win64-$ver.zip"
          Compress-Archive -Path "dist/alak.exe","pkg/README_windows.txt" -DestinationPath $zip -Force
          $sha = (Get-FileHash -Algorithm SHA256 $zip).Hash.ToLower()
          Set-Content -Path pkg/SHA256SUMS.txt -Value "$sha  $(Split-Path -Leaf $zip)"

      - name: Upload to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: ${{ github.ref_name }}
          artifacts: |
            pkg/alak-win64-${{ github.ref_name }}.zip,
            pkg/SHA256SUMS.txt
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}
